version: '2'
services:
  nginx-reverse-proxy:
    build: ./nginx-reverse-proxy
    image: tiger/reverse-proxy
    container_name: reverse-proxy
    environment:
      - DOMAIN_NAME=www.tigers-lair.com,second.tigers-lair.com
    networks:
      local:
  nginx-static-web:
    build: ./nginx-static-web
    image: tiger/nginx-static-web
    container_name: www
    networks:
      local:
  nginx-static-web-2:
    build: ./nginx-static-web-2
    image: tiger/nginx-static-web-2
    container_name: www-2
    networks:
      local:

networks:
  local:
    driver: bridge
